# Generated by Django 3.2.16 on 2023-02-23 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='adress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('address1', models.CharField(max_length=60, verbose_name='address line 1')),
                ('address2', models.CharField(blank=True, max_length=60, verbose_name='address line 2')),
                ('zip_code', models.CharField(max_length=12, verbose_name=' zip /postalcode')),
                ('city', models.CharField(max_length=60)),
                ('country', models.CharField(choices=[('uk', 'unitedkingdom'), ('us', 'united states of america'), ('eg', 'Egypt')], max_length=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
